# Generated by Django 2.0.10 on 2019-02-10 17:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('violation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default='active')),
                ('location', models.CharField(max_length=400)),
                ('details', models.TextField(blank=True, help_text='Details of sound agency/institution', null=True)),
                ('mobile_number', models.IntegerField()),
                ('issued_date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='licensee',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='violation',
            name='licensee',
        ),
        migrations.AddField(
            model_name='violation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 17, 1, 39, 510549, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='violation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Licensee',
        ),
        migrations.AddField(
            model_name='violation',
            name='license',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='violation.License'),
            preserve_default=False,
        ),
    ]
